package kamarad;


/**
* kamarad/_OnlineKamaradImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from kamarad.idl
* Wednesday, March 5, 2014 10:00:42 AM GMT
*/

public abstract class _OnlineKamaradImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements kamarad.OnlineKamarad, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _OnlineKamaradImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("register", new java.lang.Integer (0));
    _methods.put ("getAccountDetails", new java.lang.Integer (1));
    _methods.put ("topupAccount", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // kamarad/OnlineKamarad/register
       {
         kamarad.KamaradAccountDetails accountDetails = kamarad.KamaradAccountDetailsHelper.read (in);
         org.omg.CORBA.AnyHolder uniqueId = new org.omg.CORBA.AnyHolder ();
         this.register (accountDetails, uniqueId);
         out = $rh.createReply();
         out.write_any (uniqueId.value);
         break;
       }

       case 1:  // kamarad/OnlineKamarad/getAccountDetails
       {
         int uniqueId = in.read_long ();
         kamarad.KamaradAccountDetailsHolder accountDetails = new kamarad.KamaradAccountDetailsHolder ();
         this.getAccountDetails (uniqueId, accountDetails);
         out = $rh.createReply();
         kamarad.KamaradAccountDetailsHelper.write (out, accountDetails.value);
         break;
       }

       case 2:  // kamarad/OnlineKamarad/topupAccount
       {
         int uniqueId = in.read_long ();
         double amount = in.read_double ();
         this.topupAccount (uniqueId, amount);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:kamarad/OnlineKamarad:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _OnlineKamaradImplBase
