package kamarad;


/**
* kamarad/_OnlineKamaradStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from kamarad.idl
* Wednesday, March 5, 2014 10:00:42 AM GMT
*/

public class _OnlineKamaradStub extends org.omg.CORBA.portable.ObjectImpl implements kamarad.OnlineKamarad
{

  public void register (kamarad.KamaradAccountDetails accountDetails, org.omg.CORBA.AnyHolder uniqueId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("register", true);
                kamarad.KamaradAccountDetailsHelper.write ($out, accountDetails);
                $in = _invoke ($out);
                uniqueId.value = $in.read_any ();
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                register (accountDetails, uniqueId        );
            } finally {
                _releaseReply ($in);
            }
  } // register

  public void getAccountDetails (int uniqueId, kamarad.KamaradAccountDetailsHolder accountDetails)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getAccountDetails", true);
                $out.write_long (uniqueId);
                $in = _invoke ($out);
                accountDetails.value = kamarad.KamaradAccountDetailsHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getAccountDetails (uniqueId, accountDetails        );
            } finally {
                _releaseReply ($in);
            }
  } // getAccountDetails

  public void topupAccount (int uniqueId, double amount)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("topupAccount", true);
                $out.write_long (uniqueId);
                $out.write_double (amount);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                topupAccount (uniqueId, amount        );
            } finally {
                _releaseReply ($in);
            }
  } // topupAccount

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:kamarad/OnlineKamarad:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _OnlineKamaradStub
