package kamarad;

/**
* kamarad/KamaradAccountDetailsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from kamarad.idl
* Wednesday, March 5, 2014 10:00:42 AM GMT
*/

public final class KamaradAccountDetailsHolder implements org.omg.CORBA.portable.Streamable
{
  public kamarad.KamaradAccountDetails value = null;

  public KamaradAccountDetailsHolder ()
  {
  }

  public KamaradAccountDetailsHolder (kamarad.KamaradAccountDetails initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = kamarad.KamaradAccountDetailsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    kamarad.KamaradAccountDetailsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return kamarad.KamaradAccountDetailsHelper.type ();
  }

}
