package kamarad;


/**
* kamarad/KamaradAccountDetails.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from kamarad.idl
* Wednesday, March 5, 2014 10:00:42 AM GMT
*/

public final class KamaradAccountDetails implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String address = null;
  public String phoneNumber = null;
  public double credit = (double)0;
  public int uniqueId = (int)0;

  public KamaradAccountDetails ()
  {
  } // ctor

  public KamaradAccountDetails (String _name, String _address, String _phoneNumber, double _credit, int _uniqueId)
  {
    name = _name;
    address = _address;
    phoneNumber = _phoneNumber;
    credit = _credit;
    uniqueId = _uniqueId;
  } // ctor

} // class KamaradAccountDetails
