package kamarad;


/**
* kamarad/OnlineKamaradOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from kamarad.idl
* Wednesday, March 5, 2014 10:00:42 AM GMT
*/

public interface OnlineKamaradOperations 
{
  void register (kamarad.KamaradAccountDetails accountDetails, org.omg.CORBA.AnyHolder uniqueId);
  void getAccountDetails (int uniqueId, kamarad.KamaradAccountDetailsHolder accountDetails);
  void topupAccount (int uniqueId, double amount);
} // interface OnlineKamaradOperations
