package kamarad;


/**
* kamarad/OnlineKamarad.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from kamarad.idl
* Wednesday, March 5, 2014 10:00:42 AM GMT
*/

public interface OnlineKamarad extends OnlineKamaradOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface OnlineKamarad
