package kamarad;

/**
* kamarad/OnlineKamaradHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from kamarad.idl
* Wednesday, March 5, 2014 10:00:42 AM GMT
*/

public final class OnlineKamaradHolder implements org.omg.CORBA.portable.Streamable
{
  public kamarad.OnlineKamarad value = null;

  public OnlineKamaradHolder ()
  {
  }

  public OnlineKamaradHolder (kamarad.OnlineKamarad initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = kamarad.OnlineKamaradHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    kamarad.OnlineKamaradHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return kamarad.OnlineKamaradHelper.type ();
  }

}
